site: creeper.fr
url: https://creeper.fr
title: Blog de Creeper
description: Quelques articles utiles
twitter:
  username: CreeperBaie
  card: summary
  creator: CreeperBaie
author:
  twitter: creeperbaie
  name: Tristan
  avatar: https://avatars.githubusercontent.com/u/39345534?v=4
  email: admin@creeper.fr
  url: https://creeper.fr
permalink: pretty

baseurl: "https://creeper.fr"

highlighter: none

exclude:
  - .jekyll-cache
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"